M48
; DRILL file {KiCad 9.0.7} date 2026-03-02T14:05:12-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-02T14:05:12-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X65.11Y-95.218
X70.89Y-95.218
T2
X54.8Y-58.8
X55.0Y-97.2
X115.0Y-58.8
X115.0Y-96.8
M30
